################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################

- sections:
  - title: Getting Started
    link: docs/getting-started.md
    sections:
    - title: Responsive Web Design
      link: docs/getting-started/resp-view-transfernow.md
- sections: 
  - title: TN Integration Guide
    link: docs/getting-started/TN-Integration-Guide/transfernow-integration-guide.md
- sections:
  - title: Transfer via Bank Accounts
    link: docs/transfer-via-bank-accounts/transfer-via-bank-accounts.md
- sections:
  - title: Fund Transfer Services
    link: docs/fund-transfer/Fund-Transfer-Services.md
- sections:
  - title: Transfer Via Debit Cards
    link: docs/debit-card-transaction.md       
- sections:
  - title: Transfer Frequencies/Duration
    link: docs/transfer-durations.md
- sections:
  - title: Transfer Status/Limits
    link: docs/transfer-status-limits.md
- sections:
  - title: TransferNow UI Widget
    link: docs/getting-started/TN-UI-Widget/TN_Ui_Widget.md
    # sections:
    #     - title: TN UI Rendering Options
    #       link: docs/getting-started/TN-UI-Widget/TN_UI_Rendering_Options.md
    #     - title: TN UI Customization Guide
    #       link: docs/getting-started/TN-UI-Widget/TN_UI_Customization_Guide.md
- sections:
  - title: Release notes
    sections:
    - title: March 2024
      link: docs/release-notes/2022/march.md
