################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################

- sections:
  - title: Getting Started
    link: docs/getting-started.md
    sections: 
    - title: TN Integration Guide
      sections:
      - title: SSL Authentication
        link: docs/getting-started/TN-Integration-Guide/SSL-Authentication.md
        sections:
        - title: Digital Certificates
          link: docs/getting-started/TN-Integration-Guide/Digital-Certificates.md
        - title: Server Authentication 
          link: docs/getting-started/TN-Integration-Guide/Server-Authentication.md     
    - title: TN Mobile Integration Guide
      link: docs/getting-started/TN-Mobile-Integration-Guide.md
      sections:
        - title: Session Management
          link: docs/getting-started/session_management.md       
- sections:
  - title: Account to Account Transfers
    sections:
    - title: Adding an Account
      link: docs/acc-to-acc-transfer/adding-Acc.md
    - title: Deleting Accounts
      link: docs/acc-to-acc-transfer/delete-Acc.md
    - title: Manage Accounts
      link: docs/acc-to-acc-transfer/manage-Acc.md
    - title: Account Verification
      link: docs/acc-to-acc-transfer/Account-Verify/acc-verify-home.md
      sections:
      - title: Instant Verification
        link: docs/acc-to-acc-transfer/Account-Verify/Instant-Verify.md
      - title: Real Time Verification
        link: docs/acc-to-acc-transfer/Account-Verify/real-time.md
      - title: Trial Deposit Verification
        link: docs/acc-to-acc-transfer/Account-Verify/trial-verify.md
- sections:
  - title: Transfer via Debit Cards
    sections:
    - title: Adding Debit Cards
      link: docs/transfer-debit-card/adding-Acc.md
    - title: Debit Card Verification
      link: docs/transfer-debit-card/debit-cardVerify.md
    - title: Deleting Debit Cards
      link: docs/transfer-debit-card/delete-debitCard.md
    - title: Editing Debit Cards 
      link: docs/transfer-debit-card/edit-debitCard.md
- sections:
  - title: Transfer via Bank Accounts
    link: docs/transfer-via-bank-accounts/transfer-via-bank-accounts.md
- sections:
  - title: Fund Transfers
    sections:
    - title: Transfer Methods
      link: docs/fund-transfer/transfer-methods.md
    - title: Fund Transfer frequencies & Durations
      link: docs/fund-transfer/FT-freq.md
    - title: Transfer Cut-off Times
      link: docs/fund-transfer/transfer-cutOff.md
- sections:
  - title: TransferNow UI Widgets
    link: docs/getting_started/TN-UI-Widget/TN_Ui_Widget.md
- sections:
  - title: Release notes
    sections:
    - title: March 2022
      link: docs/release-notes/2022/march.md
