################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################

header:
  productionDescription: The optional Instant Transfers feature adds real-time speed to TransferNow. Through use of real-time connectivity offered by the NOWSM Network, Instant Transfers enables consumers to move money instantly between their bank accounts at different financial institutions and between their account at host institution and Debit Card.
  getStarted: docs/getting-started.md
benefits:
  - title: NOW® Network
    description: NOW Network from Fiserv enables instant transfers, which are delivered in seconds and available 24/7.
  - title: Exceptional Market Reach
    description: Enable customers to move money via checking / savings / money market accounts at every U.S.based FIs.
  - title: Streamlined Processes
    description: Manage every aspect of ACH Processing from handling expectations to managing resubmissions/inquiries.
featuredFeatures:
  - title: Multiple Transfer Speeds 
    groupName: 
    description: Give customers multiple transfer speed options from Standard ACH, and Next Day, to Next Day Good Funds or Instant.
    featured: true
    relatedDocs:
     - link: docs/fund-transfer/Fund-Transfer-Services.md
       title:
  - title: Real-Time Speed using Instant Transfer
    groupName: Account Verification
    description: Now® Network allows transferring money between two instant - enabled accounts at different financial institutions in realtime or by the next day. This removes the credit risk related to ACH-based, next day services.
    featured: true
  - title: Multiple Account Verification
    groupName: Multiple Account Verification
    description: Fiserv offers advanced alternatives to help protecting against online banking fraud. Multifactor Authentication / Account Verification enhances online security and maintain compliance.
    featured: true
    relatedDocs:
     - link: docs/transfer-via-bank-accounts/account_verification.md
       title: Account Verification
  - title: Responsive Web Design 
    groupName: Responsive Web Design
    description: Flexible, responsive design delivering outstanding results for desktop, tablet, and mobile users, ensuring a consistent experience across all devices. 
    featured: true
    relatedDocs:
     - link: docs/getting-started/resp-webdesign.md
       title: Responsive Web Design
  - title: Industry-Leading Security
    groupName: Industry-Leading Security
    description: Utilize Fiserv's top-notch risk management designed to reduce exposure to losses.
    featured: true
